### ISSUE TITLE
Memory corruption at start up on SDL build

### ISSUE THREAD

**Issue by mattuna15** [paulscottrobson/eris#25]
On both Mac OS and Arm Linux native SDL builds. Both see atic atac sprites and programs in memory at start. See attached recording.

[Screen Recording](https://www.dropbox.com/s/d8piracxlik93bl/Screen%20Recording%202020-05-11%20at%2014.43.52.mov?dl=0)

**Comment by paulscottrobson** [comment]
Documentation incomplete. It loads and runs "autoexec.prg" at the start. Sprites persist until you get rid of them ;-)
