### ISSUE TITLE
Add US keyboard as an option

### ISSUE THREAD

**Issue by OzHawk** [paulscottrobson/eris#29]
Some of us in other parts of the world are stuck with US keyboards.

It would be great if the keyboard could be an option.  It could be a compile time option (since the keyboard you use is unlikely to change once set) or a configuration file option.  If implemented as a configuration file option at boot (or runtime) it could also include other settings like default colours, default volume, key auto-repeat time, quick commands (for function keys), joystick key mappings.

**Comment by paulscottrobson** [comment]
It's designed for different kernel images for different keyboards. If you look in kernel/keyboard.map there is a file "uk.keyboard" which specifies characters or ASCII codes for each key on the keyboard matrix. Create a us.keyboard file from this (just @ and " swapped round ?) and change keyconv.py which currently has it hard coded :(

**Comment by OzHawk** [comment]
Are you OK if I add the US keyboard and add the file as an option. It will still be hardcoded at this stage, but at least it will be there as an option.
Hope you don't mind me raising issues.  I'm not sure if you're intending to continue to support and develop Eris or if you've moved on to new things.

**Comment by OzHawk** [comment]
Can I suggest that the Python script be modified to generate the headers for all the different keyboard maps in the keyboard-map directory, generating the name based on the keyboard name.  The include could then be a conditional compilation.  Each of the keyboard-map files and each of the include headers would be configured in github, and only the single file that includes the keyboard mapping would need to change to create a new build.
The include could even be controlled via a compile time definition.

**Comment by OzHawk** [comment]
Another thing related to this would be to identify the country version in the Kernel code version.

ie.   Kernel: 0.93-US  Kernal: 0.93-UK  Kernal: 0.93-EU

Just an idea.  Not sure how easy it is to implement.

**Comment by paulscottrobson** [comment]
Good idea.

**Comment by OzHawk** [comment]
OK, so I can see more now how you handle internationalisation.  The question is where you include the selection and how you get it to the required parts (I just found the messages.)
I also notice a slight inconsistency that the OCD part of me struggles with... messages.uk vs uk.keyboard.

The places where I can see it being affected by internationalisation so far are:
basic/src/basic.asm - For display of BASIC version
basic/messages  - for selection of I18N message file
kernal/keyboard-map - for selection of I18N keyboard map
kernal/system/boot.asm  - For display of Kernal version

**Comment by paulscottrobson** [comment]
Build commands now take two parameters - keyboard language and basic language, defaults being uk and uk , so to build an american version ./build us uk etc

Also displays language on bootup.
