### ISSUE TITLE
WISHLIST: Insert/Delete

### ISSUE THREAD

**Issue by OzHawk** [paulscottrobson/eris#34]
Implement Insert and Delete keys so that they add or remove spaces on the current line.

This may be complicated by lines that wrap onto a new line and push the rest of the lines on the page down.

**Comment by paulscottrobson** [comment]
Insert already exists, but it's control E. Delete is not implemented because code is stored without spaces (except in strings and comments). It's the same problem as the scrolling really, the whole screen is done in software.

**Comment by OzHawk** [comment]
The code is stored without spaces, but when you press enter while screen editting, what happens?
Does it look at the contents of the screen for the current line and then process it?
Is it a case of the BASIC code is unaware of what's on the screen?  Only the blitter knows what the screen looks like?
